add @Kiwi to trusted users
NixOS/ofborg pull request #419
Opened 2019-11-17 17:07 UTC by Kiwi

I'm trying to get more active contributing to nixpkgs so making myself known to ofborg seems like a good idea and also I'd like to add support for macOS to a few packages I already maintain sometime real soon (tm) so trusted users it is.

I'm like really trustworthy, I've had access to the community aarch64 server for months and only broke it once! Just look at my face :smirk: (jk, I haven't broken it... yet) Oh, and also @grahamc said to, so there's that. :smile:

2019-11-17 21:17 UTC, ryantm requested changes

2019-11-17 21:17 UTC, ryantm commented on config.public.json
> +	    "kiwi",
Seems like your indentation is different.

2019-11-17 21:32 UTC, Kiwi commented on config.public.json
> +	    "kiwi",
Somehow a \t snuck in... I never use tabs. Weird.

2019-11-17 22:11 UTC, ryantm approved these changes

2019-11-19 23:58 UTC, worldofpeace approved these changes

2019-11-19 23:58 UTC, worldofpeace commented
:eyes:

2019-11-29 20:07 UTC, merged

2020-12-13 21:35 UTC, Kiwi commented
It only took me a little over a year but I now have a macOS builder and have been updating and testing as much as I can on aarch64-linux, x86_64-linux, and x86_64-darwin! :smile: I still don't know how to use the bot. Anyway, I should have them all done about the same time as nixpkgs supports the new apple arm machines or at least soon after... so I'll check back in same time next year and let you know how it's going. :smiley: