Cachix
NixOS/ofborg pull request #459
Opened 2020-04-12 11:30 UTC by sorki

I have no idea what I'm doing.

2020-04-12 17:45 UTC, cole-h requested changes
I know this is just a draft, but I have a few comments and suggestions. We'll also need to add `cachix` to the environment (maybe `shell.nix`) at some point.

2020-04-12 17:45 UTC, cole-h commented on README.md
> +```
I'd also add running `nix-shell --run checkPhase --arg useNix1 false -A mozilla-rust-overlay` from the root of the repo (taken from `.travis.yml`) because that's where most of my build failures came from x)

2020-04-12 17:45 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +                .expect("All done.");
If an `expect` fires, it will result in a runtime panic. If this cannot be avoided, it would be nice to have a more descriptive message of what happened/went wrong. I might even be tempted to write the following for this branch:

```rust
            info!("Pushing to Cachix");
            cmd.arg(&cfg.cache_name)
                .arg(store_path)
                .status()
                .ok()
                .map(|res| res.success())
                .unwrap_or(false)
```

If the command failed, we return false. If the command succeeded, we return whether or not it was successful.

2020-04-12 17:45 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +fn cache_build(cfg: CachixConfig, status: BuildStatus, log: Vec<String>) -> bool {
Maybe `cache_push` would be a more appropriate name here. It doesn't look like we're building from the cache (though we are building *a* cache).

```suggestion
fn cache_push(cfg: &CachixConfig, status: BuildStatus, log: Vec<String>) -> bool {
```

My version of this function: https://gist.github.com/cole-h/00996da012d52ce8c95efb34743daf32

2020-04-12 17:45 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +        };
Since `status` is only used to check if it was a success, there's no reason to make it an argument (and lets us avoid `clone`ing it) -- just check in the `match` branch itself.

```suggestion
        let cachix_result = match &self.cachix {
            Some(conf) if status == BuildStatus::Success => {
                cache_build(conf, actions.log_snippet())
            }
            _ => {
                info!("Skipping Cachix because it was either not configured, or the build failed");

                false
            }
        };
```

We can also avoid `clone`ing the config by making `cache_build` (or `cache_push`, if I have my way) take a reference to a `CachixConfig`.

2020-04-26 13:03 UTC, sorki commented on ofborg/src/tasks/build.rs
> +                .expect("All done.");
Thanks, was struggling with this bit a bit.

2020-04-26 13:03 UTC, sorki commented on ofborg/src/tasks/build.rs
> +fn cache_build(cfg: CachixConfig, status: BuildStatus, log: Vec<String>) -> bool {
It was meant as a verb like `cache that build` but I like `cache_push` better.

2020-04-26 13:07 UTC, sorki commented on README.md
> +```
Done

2020-04-26 13:13 UTC, sorki commented
Thanks for the suggestions @cole-h. I've marked this ready for review now ;)

2020-04-26 13:20 UTC, domenkozar commented
cc @grahamc

2020-04-26 14:12 UTC, cole-h requested changes
A few more nits.

2020-04-26 14:12 UTC, cole-h commented on README.md
> +nix-shell --run checkPhase --arg useNix1 false -A mozilla-rust-overlay
Hehe, I forgot to come back and update my comment... I removed the Nix1 stuff in #460. It should just be necessary to run the following:

```suggestion
nix-shell --run checkPhase -A mozilla-rust-overlay
nix-shell --run checkPhase
```

The first one is our "Cargo pedantry" check (make sure Clippy and rustfmt are happy), while the second is what actually runs tests.

2020-04-26 14:12 UTC, cole-h commented on README.md
> +Send a PR if `check` and `test` are passing. Make sure
```suggestion
Currently, there's no easy way to set up a test instance. Feel free to
send a PR if `cargo check` and `cargo test` are passing. Make sure
```

(reflow where applicable)

2020-04-26 14:12 UTC, cole-h commented on README.md
> +which are set to `-D warnings` by `shell.nix`.
I don't think this line is necessary... who cares what's set and where :P

2020-04-26 14:12 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +        // here we start the actual nix build
```suggestion
```

This comment feels unnecessary to me. The next ~20 lines give context that I feel make it obvious that we're starting the Nix build hereabouts (especially, `self.nix.safely_build_attrs_async` and `match s.code() { ... => BuildStatus::Success`).

2020-04-26 14:12 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +        error!("Successful build with no output");
Nit, but I think makes it more readable if we separate expressions from statements.

```suggestion
        error!("Successful build with no output");
        
```

2020-04-26 14:12 UTC, cole-h commented on README.md
> +unset RUSTFLAGS
`unset` doesn't exist in the fish shell, so let's make this slightly more generalized:

```suggestion
To disable warnings as errors, run your command with an empty `RUSTFLAGS`. For example:

\```
RUSTFLAGS= cargo clippy
```

(I don't know how to escape triple backquotes inside triple backquotes, so I put a literal backslash in there, meaning you'll have to change this manually rather than just apply my suggestion...)

2020-04-26 14:12 UTC, cole-h commented on ofborg/src/tasks/githubcommentposter.rs
> +        if up {
More nits, but I'd like the longer and slightly more explicit variable name here... Feel free to disregard.

```suggestion
    if let Some(uploaded) = result.cachix_uploaded {
        if uploaded {
```

2020-04-26 14:23 UTC, sorki commented on ofborg/src/tasks/build.rs
> +        // here we start the actual nix build
It makes it easier to spot / grep for nix build, it wasn't clear to me at first and there was at least one other person asking about this.

2020-04-26 14:26 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +        // here we start the actual nix build
Then how about:

```suggestion
        // Nix build begins here
```

?

2020-04-26 14:26 UTC, sorki commented on README.md
> +which are set to `-D warnings` by `shell.nix`.
Well I've had too look it up as it was trolling me :D

2020-04-26 14:27 UTC, sorki commented on ofborg/src/tasks/build.rs
> +        // here we start the actual nix build
Sounds good!

2020-04-26 14:37 UTC, cole-h requested changes
A few more nits I missed the last time and LGTM.

2020-04-26 14:37 UTC, cole-h commented on README.md
> +nix-shell --run checkPhase
I figure it's better to explain what each command does in the README like I did earlier.

```suggestion
Be sure to test your changes by running the following commands from the root of the repository:

\```
nix-shell --run checkPhase -A mozilla-rust-overlay # checks rustfmt and Clippy
nix-shell --run checkPhase # runs actual tests
```

(again, reflow where appropriate and remove the backslash locally...)

2020-04-26 14:37 UTC, cole-h commented on README.md
> +cd ofborg # enter sub directory with Rust code
```suggestion
cd ofborg # enter subdirectory with Rust code
```

2020-04-26 14:37 UTC, cole-h commented on README.md
> +
```suggestion
```

2020-04-26 14:37 UTC, cole-h commented on README.md
> +which are set to `-D warnings` by `shell.nix`.
Well, if you want to leave it in, it'll need to be reworded, since it no longer makes sense with the current content ;)

2020-04-26 14:43 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +
There's a tab here from the previous suggestion in this area which will need to be fixed locally for `Cargo pedantry` to pass. Thanks GitHub.

2020-04-26 14:45 UTC, sorki commented on ofborg/src/tasks/build.rs
> +
Fixed with `cargo fmt`

2020-04-26 14:45 UTC, sorki commented on README.md
> +which are set to `-D warnings` by `shell.nix`.
Now it is

By default `RUSTFLAGS` contain `-D warnings` set by `shell.nix`.

2020-04-26 14:47 UTC, cole-h commented on README.md
> +\```
Don't forget these backslashes (they were just there to let the suggestions block be properly actionable).

2020-04-26 14:47 UTC, cole-h commented on README.md
> +\```
Don't forget these backslashes (they were just there to let the suggestions block be properly actionable).

2020-04-26 14:47 UTC, sorki commented on README.md
> +\```
I see, was wondering about it :)

2020-04-26 14:50 UTC, cole-h commented on README.md
> +which are set to `-D warnings` by `shell.nix`.
"`shell.nix` sets `RUSTFLAGS` to `-D warnings`, which tells clippy to treat warnings as errors." sounds better, IMHO. Otherwise, LGTM.

2020-04-26 15:19 UTC, sorki commented on README.md
> +which are set to `-D warnings` by `shell.nix`.
Thanks!

2020-04-26 15:42 UTC, cole-h approved these changes
LGTM! Thanks for dealing with my nitpicks :)

2020-04-29 22:53 UTC, cole-h requested changes

2020-04-29 22:53 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +        let store_path = log.last().unwrap();
Something I just thought of that should probably be addressed: what about when there were multiple builds, e.g. here: https://logs.nix.ci/?key=nixos/nixpkgs.82982&attempt_id=62265253-63b3-44e2-aa81-3fb8464be6ff

```
/nix/store/vb15nidh4wbsg9lrf93iv859mvkbn0pl-ripgrep-12.0.1
/nix/store/vywixxgrbrq76nbdra96h3nzrlnagq5m-zcash-2.1.1-1
/nix/store/v9c8cyl9rrspkv18w0f6b56ydb0350gf-lsd-0.17.0
```

In this case, I believe only the `lsd` path will be pushed to the cache.

2020-04-30 06:16 UTC, sorki commented on ofborg/src/tasks/build.rs
> +        let store_path = log.last().unwrap();
Good point! We can either call `cache_push` for each path or pipe them to Cachix via `stdin`. Just need to identify all the paths - maybe something like get all the last few consecutive lines matching `/nix/store` prefix?

2020-04-30 06:29 UTC, cole-h commented on ofborg/src/tasks/build.rs
> +        let store_path = log.last().unwrap();
Or, get the last `n` lines, where `n = number of built attrs`? We gate this on a successful build anyways, so this should be a safe bet (assuming that any failing build sets status to be not-`BuildStatus::Success` -- I'll have to read through the source again to be entirely certain).

Or both, as sanity checks for the other?

I'll do some brainstorming.

2021-03-01 08:13 UTC, sorki commented
I decided I don't care.

2021-03-01 08:13 UTC, closed without merging

2021-07-12 13:47 UTC, domenkozar commented
It would be great if binaries were pushed and available to users for testing.

I'm happy to sponsor a cache for ofborg if someone manages to get integration working.