config.public.json: configure systemd topic label
NixOS/ofborg pull request #545
Opened 2021-01-06 12:07 UTC by alyssais

I’ve used `nixos/modules/system/boot/systemd` to capture e.g. systemd.nix, systemd-unit-options.nix, etc. This should work as `PathTagger` just does a substring match, but I’m not sure if that’s something you’d like to depend on? If so, we’d have to move all the systemd options into a directory of their own (which might not be a bad thing anyway), or list them all out explicitly.

2021-01-07 03:35 UTC, cole-h requested changes
I think it's fine to rely on the substring. That said, do we want to add any of the tests to the list of monitored files?

2021-01-07 03:35 UTC, cole-h commented on config.public.json
> +	],
Alignment's slightly off.

```suggestion
		"6.topic: systemd": [
            "pkgs/os-specific/linux/systemd",
            "nixos/modules/system/boot/systemd"
		],
```

2021-01-07 03:40 UTC, SuperSandro2000 commented on config.public.json
> +	],
Also please do not mix tabs and spaces.

2021-01-07 18:54 UTC, cole-h approved these changes
LGTM.

~~EDIT: Waiting on Graham to fix our deployment stuff before merging (so I don't forget to deploy this afterwards).~~

2021-01-25 22:19 UTC, merged

2021-01-25 22:19 UTC, cole-h commented
A bit late, but everything's all good now. Thanks!