config.public.json: remove `tag_paths`
NixOS/ofborg pull request #553
Opened 2021-03-03 21:16 UTC by zowoq

These labels have been moved to a github action in the nixpkgs repo.

https://github.com/NixOS/nixpkgs/pull/113077

2021-03-18 19:30 UTC, cole-h requested changes

2021-03-18 19:30 UTC, cole-h commented on config.public.json
> +    "tag_paths": {},
Rather than just emptying the list, could you also remove all `tag_paths` related code? There's no point in keeping around dead code.

If you don't have the time / aren't comfortable with this, I could do it before I merge. Whatever works best for you; just let me know.

2021-03-18 22:37 UTC, zowoq commented on config.public.json
> +    "tag_paths": {},
Done. Tests pass so I'm hoping it's fine.

2021-03-21 00:23 UTC, cole-h approved these changes
Diff LGTM. Starting the deploy process soon. Once successful, I'll merge the Nixpkgs PR.

2021-03-21 00:23 UTC, merged