use upstream hubcaps
NixOS/ofborg pull request #624
Opened 2022-11-15 12:38 UTC by Artturin

ran `cargo fmt`
fixed clippy warnings

2022-11-15 12:45 UTC, Artturin commented on ofborg/Cargo.toml
> +http = "0.2"
will take a shot at updating hyper too but in a separate PR

2022-11-15 12:48 UTC, Artturin commented on ofborg/src/tasks/eval/nixpkgs.rs
> +                ImpactedMaintainers::calculate(&self.nix, dir, changed_paths, &changed_attributes);
done by `cargo fmt`

2022-11-15 15:51 UTC, cole-h requested changes

2022-11-15 15:51 UTC, cole-h commented on ofborg/src/config.rs
> +        JWTCredentials::new(self.conf.app_id, vec![0x00]).unwrap()
This still needs to be fixed.

2022-11-15 15:51 UTC, cole-h commented on ofborg/src/config.rs
> +        .unwrap()
I'd also really like to see less unwraps (even though I introduced most of these in my quick-n-dirty attempt).

2022-11-19 17:47 UTC, Artturin commented
Reminder @cole-h

2022-12-02 23:25 UTC, Artturin commented on ofborg/Cargo.toml
> +http = "0.2"
the release that caused large incompatibilities was hyper 0.11, couldn't figure out a way to update hyper

2022-12-03 19:54 UTC, cole-h commented on ofborg/src/config.rs
> +        JWTCredentials::new(self.conf.app_id, key).expect("Unable to create JWTCredentials")
Looks like the upstream expects this to be DER (the raw bytes), whereas we used to use PEM (base64-encoded). Required a small change to the ofborg infra, but otherwise works.

2022-12-03 20:00 UTC, cole-h approved these changes
OK, let's see how this goes.

2022-12-03 20:00 UTC, merged