nix: run all operations with "--option extra-experimental-features 'n…
NixOS/ofborg pull request #628
Opened 2022-12-08 07:53 UTC by Artturin

…iterals'"

https://github.com/nixos/nixpkgs/commit/92b4f173803f65531e066321934e7d1ee7eb5090

currently the tests fai

2022-12-08 11:16 UTC, vcunat commented
Example where this feature would've been desirable: https://github.com/NixOS/nixpkgs/pull/204859

2022-12-08 12:55 UTC, SuperSandro2000 commented
As the person that merged that PR: Why is ofborg not already complaining about this!?

2022-12-08 13:04 UTC, vcunat commented
Most likely it just hasn't been noticed/reported.

2022-12-21 21:10 UTC, cole-h requested changes, later dismissed

2022-12-21 21:10 UTC, cole-h commented on ofborg/src/nix.rs
>              _ => (),
Looks like we probably want a new arm for `Operation::Instantiate` -- that operation is used for the `nixos` and `nixos-options` (and others) checks.

2022-12-22 19:03 UTC, cole-h approved these changes
Let's give it  a shot.

2022-12-22 19:03 UTC, merged

2022-12-22 20:19 UTC, cole-h commented
https://github.com/NixOS/nixpkgs/pull/207318

ofborg catches url literals now.